version: "3.9"
services:
  mongodbservice:
    image: mongo:latest
    ports:
      - "27018:27018"
    container_name: mongo-track-contain
    networks:
      - tracks-network
  mysql-user-service:
    image: mysql:latest
    ports:
      - "3308:3307"
    container_name: mysql-track-container
    networks:
      - users-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: aarti
      MYSQL_PASSWORD: aaru
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  track-service:
    container_name: tracks-service
    build: Track/
    networks:
      - tracks-network
    ports:
      - "65105:65105"
    depends_on:
      - mongodbservice
    restart: always

  user-auth-service:
    container_name: users-service
    build: User/
    networks:
      - users-network
    ports:
      - "8087:8087"
    depends_on:
      - mysql-user-service
    restart: always
networks:
  users-network:
    driver: bridge
  tracks-network:
    driver: bridge







